class Spanish_Utils:
    add_spanish = {'Family Medicine': 'Family Medicine / Medicina Familiar',
                   'Cardiovascular Disease,Internal Medicine': 'Cardiovascular Disease,Internal Medicine / Enfermedad Cardiovascular, Medicina Interna',
                   'Dermatology,Family Medicine': 'Dermatology,Family Medicine / Dermatología, Medicina Familiar',
                   'Family Medicine,Infectious Diseases': 'Family Medicine,Infectious Diseases / Enfermedades infecciosas',
                   'Family Medicine,Orthopaedic Surgery': 'Family Medicine,Orthopaedic Surgery / Cirugía ortopédica',
                   'Family Medicine,Psychiatry': 'Family Medicine,Psychiatry / Medicina Familiar, Psiquiatría',
                   'Internal Medicine,Nephrology': 'Internal Medicine,Nephrology / Medicina Interna,Nefrología',
                   'Internal Medicine,Pediatrics': 'Internal Medicine,Pediatrics / Medicina Interna, Pediatría',
                   'Internal Medicine': 'Internal Medicine / Medicina interna',
                   'Pediatrics,Pediatric Neurology': 'Pediatrics,Pediatric Neurology / Pediatría,Neurología Pediátrica',
                   'Physician Assistant Pcp': 'Physician Assistant Pcp / Asistente medico pcc',
                   'Pediatrics': 'Pediatrics / Pediatría',
                   'Ophthalmology': 'Ophthalmology / Oftalmología',
                   'Optometry': 'Optometry / Optometría',
                   'Orthopaedic Surgery': 'Orthopaedic Surgery / Cirugía ortopédica',
                   'Pain Medicine': 'Pain Medicine / Medicina del dolor',
                   'Physician Assistant': 'Physician Assistant / Asistente medico',
                   'Physician Assistant PCP': 'Physician Assistant PCP / Auxiliar médico',
                   'Acupuncture': 'Acupuncture',
                   'Addiction Medicine': 'Addiction Medicine / Medicina de la adicción',
                   'Advanced Heart Failure And Transplant Cardiology': 'Advanced Heart Failure And Transplant Cardiology / Insuficiencia Cardíaca Avanzada Y Cardiología De Trasplantes',
                   'Adolescent Medicine': 'Adolescent Medicine / Medicina del adolescente',
                   'Advanced Heart Failure and Transplant Cardiology': 'Advanced Heart Failure and Transplant Cardiology / Insuficiencia Cardíaca Avanzada Y Cardiología De Trasplantes',
                   'Allergy and Immunology': 'Allergy And Immunology / Alergia e inmunología',
                   'Allergy And Immunology': 'Allergy And Immunology / Alergia e inmunología',
                   'Anesthesiology': 'Anesthesiology / Anestesiología',
                   'Audiology': 'Audiology / Audiología',
                   'Bariatric Surgery': 'Bariatric Surgery / Cirugía bariátrica',
                   'Behavior Analyst': 'Behavior Analyst / Analista de comportamiento',
                   'Brain Injury Medicine': 'Brain Injury Medicine / Medicina para lesiones cerebrales',
                   'Breast Surgery': 'Breast Surgery / Cirugía de mamas',
                   'Burn Surgery': 'Burn Surgery / Cirugía de quemaduras',
                   'Cardiac Electrophysiology': 'Cardiac Electrophysiology / Electrofisiología cardiaca',
                   'Cardiac Surgery': 'Cardiac Surgery / Cirugía cardiaca',
                   'Cardiac Electrophysiology,Cardiovascular Disease': 'Cardiac Electrophysiology,Cardiovascular Disease / Electrofisiología Cardíaca, Enfermedad Cardiovascular',
                   'Cardiac Surgery,Thoracic Surgery': 'Cardiac Surgery,Thoracic Surgery / Cirugía torácica',
                   'Cardiovascular Disease': 'Cardiovascular Disease / Enfermedad cardiovascular',
                   'Certified Nurse Midwife': 'Certified Nurse Midwife / Enfermera partera certificada',
                   'Child And Adolescent Psychiatry': 'Child And Adolescent Psychiatry / Psiquiatría Infantil y Adolescente',
                   'Child And Adolescent Psychology': 'Child And Adolescent Psychology / Psicología Infantil y Adolescente',
                   'Child Abuse Pediatrics': 'Child Abuse Pediatrics / Pediatría',
                   'Child Psychology': 'Child Psychology / Psicología infantil',
                   'Chiropractic Medicine': 'Chiropractic Medicine',
                   'Clinical Biochemical Genetics': 'Clinical Biochemical Genetics',
                   'Clinical Genetics': 'Clinical Genetics / Genética clínica',
                   'Clinical Neurophysiology': 'Clinical Neurophysiology / Neurofisiología clínica',
                   'Colon and Rectal Surgery': 'Colon And Rectal Surgery / Cirugía de colon y recto',
                   'Colon And Rectal Surgery': 'Colon And Rectal Surgery / Cirugía de colon y recto',
                   'Colon And Rectal Surgery,General Surgery': 'Colon And Rectal Surgery,General Surgery / Cirugía De Colon Y Recto, Cirugía General',
                   'Critical Care Medicine': 'Critical Care Medicine / Medicina de Terapia Intensiva',
                   'Dermatology': 'Dermatology / Dermatología',
                   'Dermatopathology': 'Dermatopathology',
                   'Critical Care Medicine,Pulmonary Disease': 'Critical Care Medicine,Pulmonary Disease / Medicina de Cuidados Críticos, Enfermedad Pulmonar',
                   'Developmental and Behavioral Pediatrics': 'Developmental And Behavioral Pediatrics / Pediatría del Desarrollo y el comportamiento',
                   'Developmental And Behavioral Pediatrics': 'Developmental And Behavioral Pediatrics / Pediatría del Desarrollo y el comportamiento',
                   'Emergency Medicine': 'Emergency Medicine / Medicina de emergencia',
                   'Emergency Medicine,Sports Medicine': 'Emergency Medicine,Sports Medicine / Medicina de Emergencia, Medicina Deportiva',
                   'Endocrinology Diabetes and Metabolism': 'Endocrinology Diabetes and Metabolism / Endocrinología Diabetes Y Metabolism',
                   'Endocrinology Diabetes And Metabolism': 'Endocrinology Diabetes and Metabolism / Endocrinología Diabetes Y Metabolism',
                   'Family Medicine - Specialist': 'Family Medicine - Specialist / Medicina familiar - Especialista',
                   'Female Pelvic Reproductive Surgery': 'Female Pelvic Reproductive Surgery / Cirugía reproductiva pélvica femenina',
                   'Gastroenterology': 'Gastroenterology / Gastroenterología',
                   'General Practice - Specialist': 'General Practice - Specialist',
                   'General Practice': 'General Practice / Medicina general',
                   'General Surgery': 'General Surgery / Cirugía General',
                   'Gynecologic Oncology': 'Gynecologic Oncology / Oncología ginecológica',
                   'Gynecology': 'Gynecology / Ginecología',
                   'Hand Surgery': 'Hand Surgery / Cirugía de la mano',
                   'Hematology': 'Hematology / Hematología',
                   'Hematology Oncology': 'Hematology Oncology / Hematología Oncología',
                   'Hospice and Palliative Medicine': 'Hospice And Palliative Medicine / Hospicio y medicina paliativa',
                   'Hospice And Palliative Medicine': 'Hospice And Palliative Medicine / Hospicio y medicina paliativa',
                   'Infectious Diseases': 'Infectious Diseases / Enfermedades infecciosas',
                   'Internal Medicine - Specialist': 'Internal Medicine - Specialist / Medicina interna - Especialista',
                   'Interventional Cardiology': 'Interventional Cardiology / Cardiología intervencionista',
                   'Interventional Radiology': 'Interventional Radiology / Radiología intervencional',
                   'Licensed Dietetic Nutritionist': 'Licensed Dietetic Nutritionist / Licenciado en nutrición y dietética',
                   'Licensed Marriage And Family Therapist': 'Licensed Marriage And Family Therapist / Terapeuta matrimonial y familiar con licencia',
                   'Licensedclinicalprofcounselor': 'Licensed clinical prof counselor / Consejera profesional licenciada',
                   'Licensedclinicalsocialworker': 'Licensed clinical social worker / Trabajadora social clínica licenciada',
                   'Maternal - Fetal Medicine': 'Maternal - Fetal Medicine / Medicina maternofetal',
                   'Medical Acupuncture': 'Medical Acupuncture',
                   'Medical Genetics': 'Medical Genetics / Genética médica',
                   'Medical Oncology': 'Medical Oncology / Oncología médica',
                   'Neonatal-Perinatal Medicine': 'Neonatal-Perinatal Medicine / Medicina neonatal y perinatal',
                   'Nephrology': 'Nephrology / Nefrología',
                   'Neurodevelopmental Disabilities': 'Neurodevelopmental Disabilities / Discapacidades del neurodesarrollo',
                   'Neurology': 'Neurology / Neurología',
                   'Neurosurgery': 'Neurosurgery / Neurocirugía',
                   'Neuropsychology': 'Neuropsychology / Neuropsicología',
                   'Nutritionist': 'Nutritionist / Nutricionista',
                   'Obstetrics and Gynecology': 'Obstetrics and Gynecology / Ginecología',
                   'Obstetrics And Gynecology': 'Obstetrics and Gynecology / Ginecología',
                   'Obstetrics And Gynecology,Psychiatry': 'Obstetrics And Gynecology,Psychiatry / Obstetricia y Ginecología, Psiquiatría',
                   # 'Ophthalmology': 'Ophthalmology / Oftalmología ',
                   # 'Optometry': 'Optometry / Optometría',
                   'Oral & Maxillofacial Surgery': 'Oral & Maxillofacial Surgery',
                   'Ophthalmology,Pediatric Ophthalmology': 'Ophthalmology,Pediatric Ophthalmology / Oftalmología, Oftalmología Pediátrica',
                   # 'Orthopaedic Surgery': 'Orthopaedic Surgery / Cirugía ortopédica',
                   'Orthopedic Oncology': 'Orthopedic Oncology / Oncología ortopédica',
                   'Oral &Amp; Maxillofacial Surgery': 'Oral & Maxillofacial Surgery / Cirugía Oral y Maxilofacial',
                   'Otolaryngology': 'Otolaryngology / Otorrinolaringología',
                   # 'Pain Medicine': 'Pain Medicine / Medicina del dolor',
                   'Pediatric Allergy and Immunology': 'Pediatric Allergy And Immunology / Alergia e inmunología',
                   'Pediatric Allergy And Immunology': 'Pediatric Allergy And Immunology / Alergia e inmunología',
                   'Pathology - Anatomic and Clinical': 'Pathology - Anatomic and Clinical',
                   'Pediatric Cardiac Surgery': 'Pediatric Cardiac Surgery / Cirugía cardiaca',
                   'Pediatric Cardiology': 'Pediatric Cardiology / Cardiología pediátrica',
                   'Pediatric Clinical Genetics': 'Pediatric Clinical Genetics / Genética clínica',
                   'Pediatric Critical Care Medicine': 'Pediatric Critical Care Medicine / Medicina de Terapia Intensiva',
                   'Pediatric Dermatology': 'Pediatric Dermatology / Dermatología',
                   'Pediatric Endocrinology': 'Pediatric Endocrinology / Endocrinología pediátrica',
                   'Pediatric Gastroenterology': 'Pediatric Gastroenterology / Gastroenterología',
                   'Pediatric Genetics': 'Pediatric Genetics / Genética pediátrica',
                   'Pediatric Hematology-Oncology': 'Pediatric Hematology-Oncology / Hematología y oncología pediátrica',
                   'Pediatric Infectious Diseases': 'Pediatric Infectious Diseases / Enfermedades infecciosas',
                   'Pediatric Nephrology': 'Pediatric Nephrology / Nefrología',
                   'Pediatric Neurodevelopmental Disabilities': 'Pediatric Neurodevelopmental Disabilities / Discapacidades del neurodesarrollo',
                   'Pediatric Neurology': 'Pediatric Neurology / Neurología',
                   'Pediatric Neuropsychology': 'Pediatric Neuropsychology / Neuropsicología Pediátrica',
                   'Pediatric Neurosurgery': 'Pediatric Neurosurgery / Neurocirugía',
                   'Pediatric Ophthalmology': 'Pediatric Ophthalmology / Oftalmología',
                   'Pediatric Orthopaedic Surgery': 'Pediatric Orthopaedic Surgery / Cirugía ortopédica',
                   'Pediatric Orthopaedic Surgery,Sports Medicine': 'Pediatric Orthopaedic Surgery,Sports Medicine / Medicina deportiva',
                   'Pediatric Otolaryngology': 'Pediatric Otolaryngology / Otorrinolaringología',
                   'Pediatric Plastic And Reconstructive Surgery': 'Pediatric Plastic And Reconstructive Surgery / Cirugía plástica y reconstructiva pediátrica',
                   'Pediatric Plastic and Reconstructive Surgery': 'Pediatric Plastic And Reconstructive Surgery / Cirugía plástica y reconstructiva pediátrica',
                   'Pediatric Physical And Rehabilitation Medicine': 'Pediatric Physical And Rehabilitation Medicine / Medicina Física y Rehabilitación Pediátrica',
                   'Pediatric Pulmonology': 'Pediatric Pulmonology / Neumología pediátrica',
                   'Pediatric Rehabilitation Medicine': 'Pediatric Rehabilitation Medicine / Medicina de rehabilitación pediátrica',
                   'Pediatric Rheumatology': 'Pediatric Rheumatology / Reumatología pediátrica',
                   'Pediatric Surgery': 'Pediatric Surgery / Cirugía pediátrica',
                   'Pediatric Transplant Hepatology': 'Pediatric Transplant Hepatology / Hepatología pediátrica y trasplante',
                   'Pediatric Urology': 'Pediatric Urology / Urología pediátrica',
                   'Pediatric Urology,Urology': 'Pediatric Urology,Urology / Urología',
                   'Pediatrics - Specialist': 'Pediatrics - Specialist / Pediatría - Especialista',
                   'Physical Medicine And Rehabilitation': 'Physical Medicine And Rehabilitation / Medicina física y rehabilitación',
                   'Physical Medicine and Rehabilitation': 'Physical Medicine And Rehabilitation / Medicina física y rehabilitación',
                   # 'Physician Assistant': 'Physician Assistant / Asistente medico',
                   'Plastic Surgery': 'Plastic Surgery / Cirugía plástica',
                   'Podiatry': 'Podiatry / Podiatría',
                   'Psychiatry': 'Psychiatry / Psiquiatría',
                   'Psychology': 'Psychology / Psicología',
                   'Pulmonary Disease': 'Pulmonary Disease / Enfermedad pulmonar',
                   'Pulmonary Disease,Sleep Medicine': 'Pulmonary Disease,Sleep Medicine / Medicina del sueño',
                   'Preventive Medicine': 'Preventive Medicine',
                   'Radiation Oncology': 'Radiation Oncology / Oncología radioterápica',
                   'Registered Dietician': 'Registered Dietician / Dietista registrada',
                   'Reproductive Endocrinology and Infertility': 'Reproductive Endocrinology And Infertility / Endocrinología de la reproducción e infertilidad',
                   'Reproductive Endocrinology And Infertility': 'Reproductive Endocrinology And Infertility / Endocrinología de la reproducción e infertilidad',
                   'Rheumatology': 'Rheumatology / Reumatología',
                   'Sleep Medicine': 'Sleep Medicine / Medicina del sueño',
                   'Speech And Language Pathology': 'Speech And Language Pathology / Patología del habla y lenguaje',
                   'Spinal Cord Injury Medicine': 'Spinal Cord Injury Medicine',
                   'Sports Medicine': 'Sports Medicine / Medicina deportiva',
                   'Surgical Critical Care': 'Surgical Critical Care / Cuidados intensivos quirúrgicos',
                   'Surgical Oncology': 'Surgical Oncology / Oncología quirúrgica',
                   'Thoracic Surgery': 'Thoracic Surgery / Cirugía torácica',
                   'Transplant Hepatology': 'Transplant Hepatology / Hepatología de trasplantes',
                   'Transplant Surgery': 'Transplant Surgery / Cirugía de trasplante',
                   'Trauma Surgery': 'Trauma Surgery / Cirugia de trauma',
                   'Undersea and Hyperbaric Medicine': 'Undersea And Hyperbaric Medicine / Medicina Submarina e Hiperbárica',
                   'Undersea And Hyperbaric Medicine': 'Undersea And Hyperbaric Medicine / Medicina Submarina e Hiperbárica',
                   'Urogynecology': 'UroGynecology / Ginecología',
                   'Urology': 'Urology / Urología',
                   'Vascular and Interventional Radiology': 'Vascular and Interventional Radiology / Radiología intervencional',
                   'Vascular And Interventional Radiology': 'Vascular and Interventional Radiology / Radiología intervencional',
                   'Vascular Neurology': 'Vascular Neurology / Neurología',
                   'Vascular Surgery': 'Vascular Surgery / Cirugía vascular',
                   'Ambulance & Van Transport': 'Ambulance & Van Transport',
                   'Ambulatory Surgery Center': 'Ambulatory Surgery Center / Centro de Cirugía Ambulatoria',
                   'Cardiac Monitoring': 'Cardiac Monitoring',
                   'Diabetic Prevention Program': 'Diabetic Prevention Program',
                   'Dialysis': 'Dialysis / Diálisis',
                   'Durable Medical Equipment': 'Durable Medical Equipment / Equipo médico duradero',
                   'Home Health': 'Home Health / Salud en el hogar',
                   'Hospice': 'Hospice / Hospicio',
                   'Hospital': 'Hospital / Hospital',
                   'Infusion/Injectables': 'Infusion/Injectables',
                   'Laboratory': 'Laboratory / Laboratorio',
                   'Orthotics & Prosthetics': 'Orthotics & Prosthetics / Ortesis y prótesis',
                   'Pediatric Hospital': 'Pediatric Hospital / Hospital',
                   'Radiology': 'Radiology / radiología',
                   'Rehab Hospital': 'Rehab Hospital / Hospital',
                   'Rehabilitation': 'Rehabilitation / Rehabilitación',
                   'Skilled Nursing Facility': 'Skilled Nursing Facility / Centro de enfermería especializado',
                   'Sleep Center': 'Sleep Center / Centro del Sueño',
                   'Urgent Care Centers': 'Urgent Care Centers / Centros de atención de urgencias',
                   'Pharmacy': 'Pharmacy / Farmacia',
                   'Oral And Maxillofacial Surgery': 'Oral And Maxillofacial Surgery / Cirugía Oral y Maxilofacial',
                   'Endodontics': 'Endodontics / Endodoncia',
                   'Periodontics': 'Periodontics / Periodoncia',
                   'Dentist': 'Dentist / Dentista',
                   'Pediatric Dentistry': 'Pediatric Dentistry / Odontología pediátrica',
                   'Dentist Anesthesiologist': 'Dentist Anesthesiologist / Anestesiólogo dentista',
                   'Orthodontics And Dentofacial Orthopedics': 'Orthodontics And Dentofacial Orthopedics / Ortodoncia y ortopedia dentofacial',
                   'Dental Public Health': 'Dental Public Health / Salud Pública Dental',
                   'Clinic/Center - Federally Qualified Health Center (FQHC)': 'Clinic/Center - Federally Qualified Health Center (FQHC) / Clínica/Centro - Servicios su-ministrados por un Centro de Salud con Calificación Federal (FQHC, en inglés)',
                   'Clinic/Center - Federally Qualified Health Center (Fqhc)': 'Clinic/Center - Federally Qualified Health Center (FQHC) / Clínica/Centro - Servicios su-ministrados por un Centro de Salud con Calificación Federal (FQHC, en inglés)',
                   'Eyewear Supplier (Equipment Not The Service)': 'Eyewear Supplier (Equipment Not The Service) / Proveedor de lentes (equipo, no el servicio)',
                   'Eyewear Supplier (Equipment not the service) - Eyewear Supplier (Equipment not the service)': 'Eyewear Supplier (Equipment Not The Service) / Proveedor de lentes (equipo, no el servicio)',
                   'Ophthalmology - Ophthalmology': 'Ophthalmology / Oftalmología',
                   'Ophthalmology - Glaucoma Specialist': 'Ophthalmology - Glaucoma Specialist / Oftalmología - Especialista en glaucoma',
                   'Ophthalmology Ophthalmic Plastic and Reconstructive Surgery': 'Ophthalmology Ophthalmic Plastic And Reconstructive Surgery / Oftalmologia Cirugia plastica y reconstructiva oftalmica',
                   'Ophthalmology Retina Specialist': 'Ophthalmology Retina Specialist / Especialista en Retina de Oftalmología',
                   'Optometrist - Corneal and Contact Management': 'Optometrist - Corneal And Contact Management / Optometrista - Gestión corneal y de contac-tos',
                   'Optometrist': 'Optometrist / Optometrista',
                   'Optometrist - Optometrist': 'Optometrist / Optometrista',
                   'Specialist - Specialist': 'Specialist - Specialist',
                   'Technician/Technologist - Optician': 'Technician/Technologist - Optician / Técnico / Tecnólogo - Óptico',
                    'Core Service Agency':'Core Service Agency / Agencia de servicios principales',
                   'Eyewear Supplier (Equipment Not The Service) - Eyewear Supplier (Equipment Not The Service)': 'Eyewear Supplier (Equipment Not The Service) - Eyewear Supplier (Equipment Not The Service) / Proveedor de gafas (equipo, no el servicio) - Proveedor de gafas (equipo, no el servicio)',
                   'Mental Health Clinic':'Mental Health Clinic / Clínica de salud mental',
                   'Long Term Acute Care': 'Long Term Acute Care / Cuidados agudos a largo plazo',
                   'Multi-Specialty - Multi-Specialty':'Multi-Specialty - Multi-Specialty / Multiespecialidad - Multiespecialidad',
                    'Psychiatry & Neurology - Neurology': 'Psychiatry & Neurology - Neurology / Psiquiatría y Neurología - Neurología',
                   'Technician/Technologist - Ocularist': 'Technician/Technologist - Ocularist / Técnico / Tecnólogo - Ocularista',
                   'Assistant Behavior Analyst': 'Assistant Behavior Analyst / Analista asistente de comportamiento',
                    'Colon And Rectal Surgery,Pediatric Surgery': 'Colon And Rectal Surgery,Pediatric Surgery / Cirugía De Colon Y Rectal,Cirugía Pediátrica',
                    'Endocrinology Diabetes And Metabolism,Family Medicine': 'Endocrinology Diabetes And Metabolism,Family Medicine / Endocrinología Diabetes Y Metabolismo, Medicina Familiar',
                    'Family Medicine,Gastroenterology': 'Family Medicine,Gastroenterology / Medicina Familiar, Gastroenterología',
                    'Family Medicine,Sports Medicine': 'Family Medicine,Sports Medicine / Medicina Familiar, Medicina Deportiva',
                    'Gastroenterology,Internal Medicine': 'Gastroenterology,Internal Medicine / Gastroenterología, Medicina Interna',
                    'Hematology,Medical Oncology': 'Hematology,Medical Oncology / Hematología, Oncología Médica',
                    'Infectious Diseases,Internal Medicine': 'Infectious Diseases,Internal Medicine / Enfermedades Infecciosas, Medicina Interna',
                    'Occupational Medicine': 'Occupational Medicine / Medicina del Trabajo',
                    'Occupational Therapy': 'Occupational Therapy / Terapia Ocupacional',
                    'Oral & Maxillofacial Surgery': 'Oral & Maxillofacial Surgery / Cirugía Oral y Maxilofacial',
                    'Physical Therapy': 'Physical Therapy / Fisioterapia',
                    'Acute Care Hospital': 'Acute Care HospitalÂ  / Hospital de cuidados intensivos',
                    'Diagnostic Radiology': 'Diagnostic Radiology / Radiología Diagnóstica',
                    'Psychiatric Hospital': 'Psychiatric Hospital / hospital psiquiátrico',
                    'Pulmonary Disease,Transplant Surgery': 'Pulmonary Disease,Transplant Surgery / Enfermedad pulmonar, cirugía de trasplante',
                    'Addiction Counselor': 'Addiction Counselor / Consejero de Adicciones',

                   }
